${BIND10HOME}/win32build/check/exceptions-all.sh && \
${BIND10HOME}/win32build/check/util-all.sh && \
${BIND10HOME}/win32build/check/log-all.sh && \
${BIND10HOME}/win32build/check/cryptolink-all.sh && \
${BIND10HOME}/win32build/check/dns++-all.sh && \
${BIND10HOME}/win32build/check/cc-all.sh && \
${BIND10HOME}/win32build/check/config-all.sh && \
${BIND10HOME}/win32build/check/acl-all.sh && \
${BIND10HOME}/win32build/check/bench-all.sh && \
${BIND10HOME}/win32build/check/asiolink-all.sh && \
${BIND10HOME}/win32build/check/asiodns-all.sh && \
${BIND10HOME}/win32build/check/nsas-all.sh && \
${BIND10HOME}/win32build/check/cache-all.sh && \
${BIND10HOME}/win32build/check/resolve-all.sh && \
${BIND10HOME}/win32build/check/datasrc-all.sh && \
${BIND10HOME}/win32build/check/server-common-all.sh && \
${BIND10HOME}/win32build/check/python-all.sh && \
${BIND10HOME}/win32build/check/dhcp++-all.sh && \
${BIND10HOME}/win32build/check/statistics-all.sh && \
${BIND10HOME}/win32build/check/cfgmgr-all.sh && \
${BIND10HOME}/win32build/check/loadzone-all.sh && \
${BIND10HOME}/win32build/check/resolver-all.sh && \
${BIND10HOME}/win32build/check/dhcp6-all.sh && \
${BIND10HOME}/win32build/check/dbutil-all.sh
